### ISSUE TITLE
みずほ銀行の追加認証で質問が表示されない

### ISSUE THREAD

**Issue by hiromu2000** [outerguy/ofxproxy#1]
題記の問題が発生しています。対応いただけないでしょうか。
![screen shot 2015-01-31 at 5 50 00 pm](https://cloud.githubusercontent.com/assets/1708361/5990684/c5a14052-a971-11e4-9b7f-0cf8cf099859.png)

**Comment by outerguy** [comment]
急ぎ修正しましたので、ご確認ください。

**Comment by hiromu2000** [comment]
早速のご対応ありがとうございます。質問が表示されるようになりました。
