### ISSUE TITLE
WAONのOFXファイルが正しくない

### ISSUE THREAD

**Issue by outerguy** [outerguy/ofxproxy#15]
履歴が0件の月がある場合、不正な明細1行が生成され、DTSTARTの値も（昇順ソートの関係で）不正となります。
Issuesにzipファイル（解析用の実行結果データ）を添付できないため、のちほどメールで送付いたします。
それと、これは提案なのですが、fi.xmlのnameタグの中身を、waonからWAON（正式表記）にしませんか?

**Comment by hiromu2000** [comment]
ご報告ありがとうございます。早速修正に取り掛かりました。
不正な明細１行が生成される問題は解決いたしました。
fi.xmlの内容については、additionalを削除し、nameをWAONに変更しました。

しかし、DTSTARTの問題は、解決方針が立ちません。明細が１件も存在しない場合のDTSTART、DTENDの扱いについて、どのようにすればよろしいでしょうか。

**Comment by outerguy** [comment]
諸々ご対応くださり、ありがとうございます。
DTSTART/DTENDにつきましては、./server.incの以下の値を用いるのが、次善の策と考えます。いずれも、8桁の文字列（YYYYMMDD）です。
・ENV_STR_DATE_TODAY：本日
・ENV_STR_DATE_PASTDAY：前月1日

**Comment by hiromu2000** [comment]
ご提案の方針で解決しようと思います。
実際、OFX2.1.1の仕様書p.86によると、「<DTSTART> is the date and time where the server began looking for information, not necessarily the date of the earliest returned information.」とあります。クライアントのリクエストの<DTSTART>が前月１日だと仮定すれば、レスポンスの<DTSTART>が前月１日とすることは、仕様に従っていると思われます。

**Comment by hiromu2000** [comment]
#16 でパッチをプルリクしました。

**Comment by outerguy** [comment]
確認の上、マージさせていただきました。
また、私の環境で問題が解消したことを確認いたしましたので、クローズさせていただきます。
ご対応くださりありがとうございます。
