### ISSUE TITLE
SBI証券の<MARGINBALANCE>と<AVAILCASH>がヘルプの内容と異なる

### ISSUE THREAD

**Issue by hiromu2000** [outerguy/ofxproxy#19]
SBI証券のヘルプには、以下のように記載があります。

> 現金残高等（合計）を<MARGINBALANCE>として出力します。
> 買付余力（3営業日後）を<AVAILCASH>として出力します。

しかし、実際は、
SBI証券口座分を<MARGINBALANCE>として、
現金残高等（合計）を<AVAILCASH>として出力しています。

ヘルプと実装を合わせたほうがよいと思います。

**Comment by outerguy** [comment]
ご指摘の通り、ヘルプと実装が整合していませんでした。実装が正しいため、ヘルプを修正しました。

**Comment by hiromu2000** [comment]
ご対応ありがとうございます。
一方で、#18 でスクリーンショットをご紹介した通り、住信SBIネット銀行と連携していない場合、「SBI証券口座分」の列が存在しません。結果として、<MARGINBALANCE>が0となってしまいます。
連携していない場合でも、<MARGINBALANCE>を正しく取得するようsbisec.incを修正したいと思います。別途プルリクをいたしますので、本件はクローズとします。
