### ISSUE TITLE
SBI証券で投資信託を購入後、約定日から精算日の期間、購入した商品がSOLDとなる。

### ISSUE THREAD

**Issue by hiromu2000** [outerguy/ofxproxy#25]
約定後、取引履歴ページには当該取引が計上されますが、約定日から精算日までの期間、保有証券ページには含まれません。
結果、下記のようにSOLDと見なされてしまいます。

そもそも、としてまで、売却後の証券をSECLISTに含めている理由は何でしょうか。

```
            <!-- SOLD -->
            <MFINFO>
                <SECINFO>
                    <SECID>
                        <UNIQUEID>XXXXXXX</UNIQUEID>
                        <UNIQUEIDTYPE>JP:HC</UNIQUEIDTYPE>
                    </SECID>
                    <SECNAME>○○ファンド</SECNAME>
                </SECINFO>
            </MFINFO>
```

**Comment by outerguy** [comment]
ご質問の前半部、「約定日から清算日までの期間」が今一つ理解できていません。
買付日の翌日以降に約定する投資信託で発生した、ということでしょうか。
買付日と約定日が等しいものでは再現しないと分かりましたが、もう少々、状況をご教示ください。

後半部については、売却の明細として&lt;SELLMF&gt;が追加されますが、そちらに&lt;UNIQUEID&gt;が埋まっており、対応する&lt;MFINFO&gt;を参照するからです。
なお、この&lt;MFINFO&gt;を削除すると、OFXAnalyzerで以下のようなワーニング（エラーではありません）が出ます。

No matching INFO security
&lt;FITID&gt;20151124000001000000
&lt;UNIQUEID&gt;4EC65201CF0AF0B59719222BD911BA0B

また、これはMicrosoft Moneyの独自機能なのかもしれませんが、&lt;SECNAME&gt;が同じものについては、&lt;UNIQUEID&gt;が異なっても、対応する有価証券をうまく認識しています。

**Comment by hiromu2000** [comment]
結果として大きなIssueではないことが判明しました。
本Issueのタイトルを「SBI証券で投資信託を購入後、約定日から精算日の期間、購入した商品がSOLDとなる」としましたが、正確には「SBI証券で投資信託を購入してから、購入した証券が保有証券ページに反映されるまでの期間、購入した商品がSOLDとなる」です。購入した証券が保有証券ページに反映されるタイミングが精算日であると勘違いをしていましたが、現時点では不明です。約定日の翌日には反映されるのかも知れません。

これ以降、順を追って説明します。

まず、用語の意味を整理したいと思います。
約定日：買い注文や売り注文が成立した日
精算日（＝受渡日）：売買の決済をする日
http://faq.sbisec.co.jp/faq_detail.html?id=24948

国内株式の場合、約定日から起算して4営業日目が受渡日となります。SBI証券の投資信託の場合は、不明ですが、野村證券の投資信託の場合、約定日から起算して4、5、又は6営業日目が受渡日となります。いずれにしろ、約定日の数営業日後が精算日となります。
https://www.nomura.co.jp/hometrade/help/confirm/P03_001_003.html

「買付日の翌日以降に約定する投資信託で発生した、」とありますが、私の理解では買付日＝約定日で、アウター・ガイ様の意味するところの買付日は注文日であると理解しています。

より具体的にお伝えするために、SBI証券のページのスクリーンショットを添付します。
下図は取引履歴のページです。投資信託XXXXが12/22に約定し、精算日が12/29であることがわかります。
<img width="570" alt="screen shot 2015-12-24 at 11 39 52 am" src="https://cloud.githubusercontent.com/assets/1708361/11988463/7ea29e44-aa33-11e5-8b13-c0d1f29d80d1.png">

下図は保有証券のページです。12/24の時点では、投資信託XXXXが計上されています。このため、12/24の時点では、SOLDと見なされてしまう問題は発生しません。
言い訳となりますが、12/22の時点では計上されていませんでした。
<img width="571" alt="screen shot 2015-12-24 at 12 00 33 pm" src="https://cloud.githubusercontent.com/assets/1708361/11988611/fadb9180-aa35-11e5-9e22-5b8744ba8c58.png">

SBI証券のバッチ処理のタイミングに依存するのでしょうが、取引履歴ページは即時更新であるのに対して、保有証券ページは即時には更新されません。このタイミングのずれが事の本質です。

**Comment by outerguy** [comment]
&gt; 「買付日の翌日以降に約定する投資信託で発生した、」とありますが、
&gt; 私の理解では買付日＝約定日で、アウター・ガイ様の意味するところの
&gt; 買付日は注文日であると理解しています。
仰る通り、「注文日と約定日が異なる投資信託で発生した、…」が適切ですね。
その上で、発生タイミングはこちらでなく、バッチ処理のタイミングだろうということで、理解しました。

蛇足ですが、SBI証券の投資信託関連のバッチ処理は随分と時間がかかるようで、昨日分の基準価額が反映されるのは、当日の4:30頃だったりします。運用会社は、昨日の20:00頃までには確定値を開示しているのですが…。
